#!/bin/sh

[ -f /etc/config/easytier ] || exit 0

uci -q batch <<'EOF'
set easytier.@easytier[0].easytierbin='/tmp/easytier-core'
set easytier.@easytier[0].webbin='/tmp/easytier-web'
commit easytier
EOF

exit 0
